### PR TITLE
feat(rsk): RSK Protocol & ERC20 

### PR DESCRIPTION
**Pull request by 7alip**
Hi!

This PR was created to be used if the following RSK protocol feature is to be implemented.

airgap-it/airgap-coin-lib#24
airgap-it/airgap-angular-components#1

### CODE REVIEW

**Comment by alepc253** [comment]
@pascuin @AndreasGassmann are you interested in integrating RSK (Rootstock)? We can work again on the pull requests and make them mergeable but we need to know if you will consider them

**Comment by alepc253** [comment]
@AndreasGassmann hey, would you consider the integration?

**Comment by adil651** [comment]
Hi, Please see attached video for RNS multichain resolution.
If the user is on RBTC wallet, the multichain resolves the Rootstock address but if the user is on any other wallet, depending on the network, the multichain support resolves address for that network if the user have already set it on our domain management platform. In given video, the user has not setup Bitcoin address, so no address is resolved. Please let me know if anything is not clear. 
Have a nice day
Thank you

https://user-images.githubusercontent.com/25885296/235094660-69200663-8282-4dc0-b574-49208f2d1385.mp4

**Comment by mlaeng** [comment]
RSK was added into AirGap Wallet in version 3.30.0: https://github.com/airgap-it/airgap-wallet/releases/tag/v3.30.0

Thank you for your contribution!

**Pull request closed without merging**
