### PR TITLE
Added Spanish Translation and the ability to detect and use browser language

### PR DESCRIPTION
**Pull request by fmendoza**

### CODE REVIEW

**Comment by AndreasGassmann** [comment]
Could you maybe change the permissions of some of the files back so we can see the diff? I'll probably have time to review it tomorrow.

**Comment by pascuin** [comment]
@fmendoza would be great if you could do the changes @AndreasGassmann mentioned, then we can merge it back and use it. Thank you for your effort!

**Comment by AndreasGassmann** [comment]
@fmendoza We have changed many things since you forked our repo back in September. Both our apps are now fully translatable.

If you are still interested in adding your translations, you can fork the newest version and then simply add your translation file for Spanish.

Thanks again for your work!

**Comment by AndreasGassmann** [comment]
Closing due to #5

**Pull request closed without merging**
